INSERT INTO products (
  id,
  slug,
  name,
  description,
  price_cents,
  currency,
  active,
  file_key,
  product_type,
  affiliate_url,
  affiliate_source,
  display_price,
  image_url,
  image_alt,
  badge,
  featured_rank,
  category,
  collection
) VALUES
  (
    gen_random_uuid(),
    'logitech-g502-hero-mouse',
    'Logitech G502 HERO Gaming Mouse',
    'Flagship wired mouse with HERO sensor, 11 programmable buttons, and adjustable weights.',
    100,
    'USD',
    true,
    'logitech-g502-hero-mouse',
    'affiliate',
    'https://www.amazon.com/dp/B07GBZ4Q68/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mouse.svg',
    'Logitech G502 HERO gaming mouse',
    'Top pick',
    1,
    'mouse',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'keychron-k2-mechanical-keyboard',
    'Keychron K2 Wireless Mechanical Keyboard',
    'Compact 75% layout with Bluetooth multi-device support and USB-C wired mode.',
    100,
    'USD',
    true,
    'keychron-k2-mechanical-keyboard',
    'affiliate',
    'https://www.amazon.com/dp/B07Y9Y69N7/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/keyboard.svg',
    'Keychron K2 wireless mechanical keyboard',
    'Best for typing',
    2,
    'keyboard',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'keychron-k10-v2-mechanical-keyboard',
    'Keychron K10 V2 Full-Size Mechanical Keyboard',
    'Full 104-key layout with wired and Bluetooth connectivity for long coding sessions.',
    100,
    'USD',
    true,
    'keychron-k10-v2-mechanical-keyboard',
    'affiliate',
    'https://www.amazon.com/dp/B0DSP9M2VT/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/keyboard.svg',
    'Keychron K10 V2 full-size mechanical keyboard',
    'Full-size comfort',
    null,
    'keyboard',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'elgato-stream-deck-mk2',
    'Elgato Stream Deck MK.2',
    '15-key LCD pad for streamers and productivity workflows.',
    100,
    'USD',
    true,
    'elgato-stream-deck-mk2',
    'affiliate',
    'https://www.amazon.com/dp/B09738CV2G/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/deck.svg',
    'Elgato Stream Deck MK.2 control pad',
    'Workflow boost',
    3,
    'streamdeck',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'logitech-yeti-usb-microphone',
    'Logitech G Yeti USB Microphone',
    'Multi-pattern mic with Blue VO!CE effects for streaming, podcasting, and calls.',
    100,
    'USD',
    true,
    'logitech-yeti-usb-microphone',
    'affiliate',
    'https://www.amazon.com/dp/B00N1YPXW2/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mic.svg',
    'Logitech G Yeti USB microphone',
    'Creator favorite',
    4,
    'audio',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'amazon-eero-max-7',
    'Amazon eero Max 7 Mesh Wi-Fi Router',
    'Wi-Fi 7 mesh router built for multi-gig plans and 2,500 sq ft coverage.',
    100,
    'USD',
    true,
    'amazon-eero-max-7',
    'affiliate',
    'https://www.amazon.com/dp/B09HJJN7MS/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/router.svg',
    'Amazon eero Max 7 mesh Wi-Fi router',
    'Wi-Fi 7',
    null,
    'network',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'obsbot-tail-air-smart-remote',
    'OBSBOT Tail Air & Smart Remote Combo',
    'AI-powered PTZ camera with 4K/60fps, gesture control, and remote.',
    100,
    'USD',
    true,
    'obsbot-tail-air-smart-remote',
    'affiliate',
    'https://www.amazon.com/dp/B0CT8X16NV/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/camera.svg',
    'OBSBOT Tail Air PTZ camera with remote',
    'AI PTZ',
    null,
    'camera',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'enabot-ebo-se-camera-robot',
    'Enabot EBO SE FamilyBot Camera Robot',
    '1080P mobile camera robot with night vision, two-way talk, and auto-charging.',
    100,
    'USD',
    true,
    'enabot-ebo-se-camera-robot',
    'affiliate',
    'https://www.amazon.com/dp/B09R6V3CJM/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/robot.svg',
    'Enabot EBO SE camera robot',
    'Family bot',
    null,
    'robot',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'funko-pop-darth-vader-64557',
    'Funko Pop! Darth Vader (64557)',
    '5-inch vinyl bobblehead from the Obi-Wan Kenobi series for desk flair.',
    100,
    'USD',
    true,
    'funko-pop-darth-vader-64557',
    'affiliate',
    'https://www.amazon.com/dp/B0BD67CKDB/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/funko.svg',
    'Funko Pop Darth Vader collectible',
    'Desk flair',
    null,
    'collectible',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'arduino-uno-rev3',
    'Arduino Uno Rev3 Board',
    'ATmega328P-based microcontroller board for prototyping and DIY projects.',
    100,
    'USD',
    true,
    'arduino-uno-rev3',
    'affiliate',
    'https://www.amazon.com/dp/B008GRTSV6/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/microcontroller.svg',
    'Arduino Uno Rev3 board',
    'Starter board',
    null,
    'maker',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'raspberry-pi-4-model-b',
    'Raspberry Pi 4 Model B (4 GB)',
    '4 GB single-board computer with dual 4K display support for home lab builds.',
    100,
    'USD',
    true,
    'raspberry-pi-4-model-b',
    'affiliate',
    'https://www.amazon.com/dp/B07TC2BK1X/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/pi.svg',
    'Raspberry Pi 4 Model B single-board computer',
    'Home lab staple',
    null,
    'pi',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'lego-mandalorian-helmet-75328',
    'LEGO Star Wars The Mandalorian Helmet (75328)',
    'Display-quality helmet build with 584 pieces for focused breaks.',
    100,
    'USD',
    true,
    'lego-mandalorian-helmet-75328',
    'affiliate',
    'https://www.amazon.com/dp/B09JKZM4CM/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Mandalorian Helmet set',
    'Display build',
    null,
    'lego',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'lego-luke-xwing-75301',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter (75301)',
    'Detailed X-Wing build with adjustable wings and minifigures.',
    100,
    'USD',
    true,
    'lego-luke-xwing-75301',
    'affiliate',
    'https://www.amazon.com/dp/B08G4GP34B/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter set',
    'Classic build',
    null,
    'lego',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'you-dont-know-js-yet-get-started',
    'You Don’t Know JS Yet: Get Started',
    'Concise JavaScript primer that dives into core language mechanics.',
    100,
    'USD',
    true,
    'you-dont-know-js-yet-get-started',
    'affiliate',
    'https://www.amazon.com/dp/B084BNMN7T/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'You Don’t Know JS Yet: Get Started book',
    'JS fundamentals',
    null,
    'book',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'javascript-crash-course-nick-morgan',
    'JavaScript Crash Course (Nick Morgan)',
    'Project-based JavaScript lessons for a fast, hands-on refresh.',
    100,
    'USD',
    true,
    'javascript-crash-course-nick-morgan',
    'affiliate',
    'https://www.amazon.com/dp/1718502265/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'JavaScript Crash Course by Nick Morgan',
    'Project-based',
    null,
    'book',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'dnd-players-handbook-2024',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Updated core rulebook with revised classes, feats, and spells.',
    100,
    'USD',
    true,
    'dnd-players-handbook-2024',
    'affiliate',
    'https://www.amazon.com/dp/0786969512/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Tabletop essential',
    null,
    'book',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'logitech-mx-master-3s',
    'Logitech MX Master 3S',
    'Silent productivity mouse built for office and dev work.',
    100,
    'USD',
    true,
    'logitech-mx-master-3s',
    'affiliate',
    'https://www.amazon.com/dp/B09HM94VDS/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mouse.svg',
    'Logitech MX Master 3S mouse',
    'Productivity',
    null,
    'mouse',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'elgato-wave-3',
    'Elgato Wave:3 USB Microphone',
    'USB mic with Wave Link mixing for clean desk audio.',
    100,
    'USD',
    true,
    'elgato-wave-3',
    'affiliate',
    'https://www.amazon.com/dp/B088HHWC47/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mic.svg',
    'Elgato Wave:3 USB microphone',
    'Desk audio',
    null,
    'audio',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'elgato-key-light-air',
    'Elgato Key Light Air',
    'Studio-ready lighting without ring-light vibes.',
    100,
    'USD',
    true,
    'elgato-key-light-air',
    'affiliate',
    'https://www.amazon.com/dp/B082QHRZFW/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/light.svg',
    'Elgato Key Light Air panel',
    'Lighting',
    null,
    'light',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'sony-zv-e10',
    'Sony ZV-E10 Mirrorless Camera (Body Only)',
    'Creator-focused mirrorless body for serious video upgrades.',
    100,
    'USD',
    true,
    'sony-zv-e10',
    'affiliate',
    'https://www.amazon.com/dp/B09BBGN298/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/camera.svg',
    'Sony ZV-E10 mirrorless camera body',
    'Creator cam',
    null,
    'camera',
    'Core Desk & Streaming'
  ),
  (
    gen_random_uuid(),
    'raspberry-pi-5-8gb',
    'Raspberry Pi 5 (8 GB)',
    'Modern Pi with 8 GB RAM for home lab and projects.',
    100,
    'USD',
    true,
    'raspberry-pi-5-8gb',
    'affiliate',
    'https://www.amazon.com/dp/B0CK2FCG1K/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/pi.svg',
    'Raspberry Pi 5 8 GB board',
    'Latest Pi',
    null,
    'pi',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'canakit-raspberry-pi-5-kit',
    'CanaKit Raspberry Pi 5 Starter Kit (8 GB)',
    'Complete kit that converts better than bare boards.',
    100,
    'USD',
    true,
    'canakit-raspberry-pi-5-kit',
    'affiliate',
    'https://www.amazon.com/dp/B0CK4ZB6RN/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/pi.svg',
    'CanaKit Raspberry Pi 5 starter kit',
    'Full kit',
    null,
    'pi',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'arduino-starter-kit',
    'Arduino Starter Kit (Official)',
    'Official Arduino starter kit for beginners.',
    100,
    'USD',
    true,
    'arduino-starter-kit',
    'affiliate',
    'https://www.amazon.com/dp/B009UKZV0A/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/microcontroller.svg',
    'Arduino Starter Kit',
    'Beginner kit',
    null,
    'maker',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'saleae-logic-8',
    'Saleae Logic 8 USB Logic Analyzer',
    'Signals real hardware dev, not hobby-only.',
    100,
    'USD',
    true,
    'saleae-logic-8',
    'affiliate',
    'https://www.amazon.com/dp/B01N7N3KNS/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/microcontroller.svg',
    'Saleae Logic 8 USB logic analyzer',
    'Hardware dev',
    null,
    'maker',
    'Home Lab & Maker Gear'
  ),
  (
    gen_random_uuid(),
    'designing-data-intensive-applications',
    'Designing Data-Intensive Applications',
    'Modern systems classic for serious engineering depth.',
    100,
    'USD',
    true,
    'designing-data-intensive-applications',
    'affiliate',
    'https://www.amazon.com/dp/1449373321/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'Designing Data-Intensive Applications book',
    'Dev classic',
    null,
    'book',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'clean-architecture-uncle-bob',
    'Clean Architecture (Robert C. Martin)',
    'Evergreen software design book that still converts.',
    100,
    'USD',
    true,
    'clean-architecture-uncle-bob',
    'affiliate',
    'https://www.amazon.com/dp/0134494164/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'Clean Architecture by Robert C. Martin',
    'Architecture',
    null,
    'book',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'lego-atari-2600',
    'LEGO Icons Atari 2600 Console',
    'Tech nostalgia with adult LEGO appeal.',
    100,
    'USD',
    true,
    'lego-atari-2600',
    'affiliate',
    'https://www.amazon.com/dp/B0B4J6RC8N/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Icons Atari 2600 console set',
    'Retro build',
    null,
    'lego',
    'Learning & Hobby'
  ),
  (
    gen_random_uuid(),
    'funko-pop-r2d2-deluxe',
    'Funko Pop! R2-D2 (Deluxe)',
    'Pairs well with Vader without repeating characters.',
    100,
    'USD',
    true,
    'funko-pop-r2d2-deluxe',
    'affiliate',
    'https://www.amazon.com/dp/B09T5B8K4S/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/funko.svg',
    'Funko Pop R2-D2 deluxe collectible',
    'Desk flair',
    null,
    'collectible',
    'Learning & Hobby'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  active = EXCLUDED.active,
  file_key = EXCLUDED.file_key,
  product_type = EXCLUDED.product_type,
  affiliate_url = EXCLUDED.affiliate_url,
  affiliate_source = EXCLUDED.affiliate_source,
  display_price = EXCLUDED.display_price,
  image_url = EXCLUDED.image_url,
  image_alt = EXCLUDED.image_alt,
  badge = EXCLUDED.badge,
  featured_rank = EXCLUDED.featured_rank,
  category = EXCLUDED.category,
  collection = EXCLUDED.collection;

UPDATE products
SET active = false
WHERE slug = 'example-product';
