INSERT INTO products (
  id,
  slug,
  name,
  description,
  price_cents,
  currency,
  active,
  file_key,
  product_type,
  affiliate_url,
  affiliate_source,
  display_price,
  image_url,
  image_alt,
  badge,
  featured_rank,
  category,
  collection
) VALUES
  (
    gen_random_uuid(),
    'logitech-g502-hero-mouse',
    'Logitech G502 HERO Gaming Mouse',
    'Wired gaming mouse with HERO sensor, adjustable weights, and 11 programmable buttons.',
    100,
    'USD',
    true,
    'logitech-g502-hero-mouse',
    'affiliate',
    'https://www.amazon.com/dp/B07GBZ4Q68/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mouse.svg',
    'Logitech G502 HERO gaming mouse',
    'Top pick',
    1,
    'mouse',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'keychron-k2-mechanical-keyboard',
    'Keychron K2 Wireless Mechanical Keyboard',
    'Wireless mechanical keyboard with Bluetooth multi-device support and USB-C wired mode.',
    100,
    'USD',
    true,
    'keychron-k2-mechanical-keyboard',
    'affiliate',
    'https://www.amazon.com/dp/B07Y9Y69N7/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/keyboard.svg',
    'Keychron K2 wireless mechanical keyboard',
    'Best for typing',
    2,
    'keyboard',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'elgato-stream-deck-mk2',
    'Elgato Stream Deck MK.2',
    '15-key customizable LCD control pad for workflows, streaming, and automation.',
    100,
    'USD',
    true,
    'elgato-stream-deck-mk2',
    'affiliate',
    'https://www.amazon.com/dp/B09738CV2G/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/deck.svg',
    'Elgato Stream Deck MK.2 control pad',
    'Workflow boost',
    3,
    'streamdeck',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'arduino-uno-rev3',
    'Arduino Uno Rev3',
    'ATmega328P-based microcontroller board with digital and analog I/O for projects and learning.',
    100,
    'USD',
    true,
    'arduino-uno-rev3',
    'affiliate',
    'https://www.amazon.com/dp/B008GRTSV6/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/microcontroller.svg',
    'Arduino Uno Rev3 board',
    'Starter kit',
    null,
    'maker',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'raspberry-pi-4-model-b',
    'Raspberry Pi 4 Model B',
    'Compact single-board computer capable of dual 4K display output and desktop-style performance.',
    100,
    'USD',
    true,
    'raspberry-pi-4-model-b',
    'affiliate',
    'https://www.amazon.com/dp/B07TC2BK1X/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/pi.svg',
    'Raspberry Pi 4 Model B single-board computer',
    'Mini powerhouse',
    null,
    'pi',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'logitech-yeti-usb-microphone',
    'Logitech G Yeti USB Microphone',
    'Multi-pattern USB microphone with Blue VO!CE effects for streaming, podcasts, and calls.',
    100,
    'USD',
    true,
    'logitech-yeti-usb-microphone',
    'affiliate',
    'https://www.amazon.com/dp/B00N1YPXW2/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mic.svg',
    'Logitech G Yeti USB microphone',
    'Creator favorite',
    4,
    'audio',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'dnd-players-handbook-2024',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Updated Player’s Handbook with revised classes, species, feats, and spells for 5e play.',
    100,
    'USD',
    true,
    'dnd-players-handbook-2024',
    'affiliate',
    'https://www.amazon.com/dp/0786969512/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Must-have',
    null,
    'tabletop',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'lego-mandalorian-helmet-75328',
    'LEGO Star Wars The Mandalorian Helmet (75328)',
    'Buildable Mandalorian helmet display set (75328) with 584 pieces.',
    100,
    'USD',
    true,
    'lego-mandalorian-helmet-75328',
    'affiliate',
    'https://www.amazon.com/dp/B09JKZM4CM/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Mandalorian Helmet set',
    'Display piece',
    null,
    'lego',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'lego-luke-xwing-75301',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter (75301)',
    'Detailed X-Wing build with adjustable wings and minifigures (set 75301).',
    100,
    'USD',
    true,
    'lego-luke-xwing-75301',
    'affiliate',
    'https://www.amazon.com/dp/B08G4GP34B/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter set',
    'Classic build',
    null,
    'lego',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'funko-pop-darth-vader-64557',
    'Funko Pop! Darth Vader (64557)',
    'Vinyl Darth Vader bobblehead from the Obi-Wan Kenobi series, approx. 5 in tall.',
    100,
    'USD',
    true,
    'funko-pop-darth-vader-64557',
    'affiliate',
    'https://www.amazon.com/dp/B0BD67CKDB/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/funko.svg',
    'Funko Pop Darth Vader collectible',
    'Desk flair',
    null,
    'collectible',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'amazon-eero-max-7-router',
    'Amazon eero Max 7 Mesh Wi-Fi Router',
    'Tri-band Wi-Fi 7 router with 2.4/5/6 GHz bands, four high-speed Ethernet ports, and 2,500 sq ft coverage per unit.',
    100,
    'USD',
    true,
    'amazon-eero-max-7-router',
    'affiliate',
    'https://www.amazon.com/dp/B09HJJN7MS/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/router.svg',
    'Amazon eero Max 7 mesh Wi-Fi router',
    'Wi-Fi 7',
    null,
    'network',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'keychron-k10-v2-keyboard',
    'Keychron K10 V2 Full-Size Mechanical Keyboard',
    'Full-size 104-key wireless mechanical keyboard with QMK/VIA support.',
    100,
    'USD',
    true,
    'keychron-k10-v2-keyboard',
    'affiliate',
    'https://www.amazon.com/dp/B0DSP9M2VT/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/keyboard.svg',
    'Keychron K10 V2 full-size keyboard',
    'Full size',
    null,
    'keyboard',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'enabot-ebo-se-camera-robot',
    'Enabot EBO SE FamilyBot Camera Robot',
    'Mobile 360° home camera robot with auto-cruise security and two-way audio.',
    100,
    'USD',
    true,
    'enabot-ebo-se-camera-robot',
    'affiliate',
    'https://www.amazon.com/dp/B09R6V3CJM/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/robot.svg',
    'Enabot EBO SE camera robot',
    'Home robot',
    null,
    'robot',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'you-dont-know-js-get-started',
    'You Don''t Know JS Yet: Get Started (2nd Edition)',
    'Starter volume of the You Don’t Know JS Yet series.',
    100,
    'USD',
    true,
    'you-dont-know-js-get-started',
    'affiliate',
    'https://www.amazon.com/dp/B084BNMN7T/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'You Don’t Know JS Yet: Get Started book',
    'Learn JS',
    null,
    'book',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'javascript-crash-course-book',
    'JavaScript Crash Course',
    'Project-based JavaScript intro from No Starch Press.',
    100,
    'USD',
    true,
    'javascript-crash-course-book',
    'affiliate',
    'https://www.amazon.com/dp/1718502265/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'JavaScript Crash Course book',
    'Hands-on',
    null,
    'book',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'carl-bloch-roman-osteria-print',
    'Carl Bloch “In a Roman Osteria” Art Print',
    'Official art print with premium paper and UV-resistant finish.',
    100,
    'USD',
    true,
    'carl-bloch-roman-osteria-print',
    'affiliate',
    'https://www.posterlounge.com/p/1145267.html',
    'Posterlounge',
    'See price at Posterlounge',
    '/store/art.svg',
    'Carl Bloch “In a Roman Osteria” art print',
    'Art print',
    null,
    'art',
    'Partner Picks'
  ),
  (
    gen_random_uuid(),
    'obsbot-tail-air-remote-combo',
    'OBSBOT Tail Air + Smart Remote Combo',
    'AI-powered PTZ camera with 4K capture and smart remote control.',
    100,
    'USD',
    true,
    'obsbot-tail-air-remote-combo',
    'affiliate',
    'https://www.fullcompass.com/prod/633036-obsbot-tail-air-remote-combo',
    'Full Compass',
    'See price at Full Compass',
    '/store/camera.svg',
    'OBSBOT Tail Air camera and smart remote combo',
    'Streaming camera',
    null,
    'camera',
    'Partner Picks'
  ),
  (
    gen_random_uuid(),
    'obsbot-tail-air-amazon',
    'OBSBOT Tail Air Streaming Camera',
    'AI-powered PTZ streaming camera with smart tracking and 4K capture.',
    100,
    'USD',
    true,
    'obsbot-tail-air-amazon',
    'affiliate',
    'https://www.amazon.com/dp/B0CT8X16NV/?tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/camera.svg',
    'OBSBOT Tail Air streaming camera',
    'Creator cam',
    null,
    'camera',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    '127-0-0-1-tshirt',
    '“There is no place like 127.0.0.1” T-shirt',
    'Classic developer tee with multiple sizes and fits.',
    100,
    'USD',
    true,
    '127-0-0-1-tshirt',
    'affiliate',
    'https://www.teepublic.com/t-shirt/10133105-there-is-no-place-like-127-0-0-1',
    'TeePublic',
    'See price at TeePublic',
    '/store/shirt.svg',
    'There is no place like 127.0.0.1 t-shirt',
    'Apparel',
    null,
    'apparel',
    'Partner Picks'
  ),
  (
    gen_random_uuid(),
    'ydkjs-get-started-leanpub',
    'You Don''t Know JS Yet: Get Started (Ebook)',
    'Leanpub edition covering JS fundamentals and how the language works.',
    100,
    'USD',
    true,
    'ydkjs-get-started-leanpub',
    'affiliate',
    'https://leanpub.com/ydkjsy-get-started',
    'Leanpub',
    'From $18.95 at Leanpub',
    '/store/book.svg',
    'You Don’t Know JS Yet: Get Started Leanpub ebook',
    'Ebook',
    null,
    'book',
    'Partner Picks'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  active = EXCLUDED.active,
  file_key = EXCLUDED.file_key,
  product_type = EXCLUDED.product_type,
  affiliate_url = EXCLUDED.affiliate_url,
  affiliate_source = EXCLUDED.affiliate_source,
  display_price = EXCLUDED.display_price,
  image_url = EXCLUDED.image_url,
  image_alt = EXCLUDED.image_alt,
  badge = EXCLUDED.badge,
  featured_rank = EXCLUDED.featured_rank,
  category = EXCLUDED.category,
  collection = EXCLUDED.collection;

UPDATE products
SET active = false
WHERE slug = 'example-product';
