INSERT INTO products (
  id,
  slug,
  name,
  description,
  price_cents,
  currency,
  active,
  file_key,
  product_type,
  affiliate_url,
  affiliate_source,
  display_price,
  image_url,
  image_alt,
  badge,
  featured_rank,
  category,
  collection
) VALUES
  (
    gen_random_uuid(),
    'logitech-g502-hero-mouse',
    'Logitech G502 HERO Gaming Mouse',
    'Wired gaming mouse with HERO sensor, adjustable weights, and 11 programmable buttons.',
    100,
    'USD',
    true,
    'logitech-g502-hero-mouse',
    'affiliate',
    'https://www.amazon.com/s?k=Logitech+G502+HERO&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mouse.svg',
    'Logitech G502 HERO gaming mouse',
    'Top pick',
    1,
    'mouse',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'keychron-k2-mechanical-keyboard',
    'Keychron K2 Wireless Mechanical Keyboard',
    'Wireless mechanical keyboard with Bluetooth multi-device support and USB-C wired mode.',
    100,
    'USD',
    true,
    'keychron-k2-mechanical-keyboard',
    'affiliate',
    'https://www.amazon.com/s?k=Keychron+K2+wireless+mechanical+keyboard&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/keyboard.svg',
    'Keychron K2 wireless mechanical keyboard',
    'Best for typing',
    2,
    'keyboard',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'elgato-stream-deck-mk2',
    'Elgato Stream Deck MK.2',
    '15-key customizable LCD control pad for workflows, streaming, and automation.',
    100,
    'USD',
    true,
    'elgato-stream-deck-mk2',
    'affiliate',
    'https://www.amazon.com/s?k=Elgato+Stream+Deck+MK.2&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/deck.svg',
    'Elgato Stream Deck MK.2 control pad',
    'Workflow boost',
    3,
    'streamdeck',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'arduino-uno-rev3',
    'Arduino Uno Rev3',
    'ATmega328P-based microcontroller board with digital and analog I/O for projects and learning.',
    100,
    'USD',
    true,
    'arduino-uno-rev3',
    'affiliate',
    'https://www.amazon.com/s?k=Arduino+Uno+Rev3&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/microcontroller.svg',
    'Arduino Uno Rev3 board',
    'Starter kit',
    null,
    'maker',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'raspberry-pi-4-model-b',
    'Raspberry Pi 4 Model B',
    'Compact single-board computer capable of dual 4K display output and desktop-style performance.',
    100,
    'USD',
    true,
    'raspberry-pi-4-model-b',
    'affiliate',
    'https://www.amazon.com/s?k=Raspberry+Pi+4+Model+B&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/pi.svg',
    'Raspberry Pi 4 Model B single-board computer',
    'Mini powerhouse',
    null,
    'pi',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'logitech-yeti-usb-microphone',
    'Logitech G Yeti USB Microphone',
    'Multi-pattern USB microphone with Blue VO!CE effects for streaming, podcasts, and calls.',
    100,
    'USD',
    true,
    'logitech-yeti-usb-microphone',
    'affiliate',
    'https://www.amazon.com/s?k=Logitech+Yeti+USB+Microphone&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/mic.svg',
    'Logitech G Yeti USB microphone',
    'Creator favorite',
    4,
    'audio',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'dnd-players-handbook-2024',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Updated Player’s Handbook with revised classes, species, feats, and spells for 5e play.',
    100,
    'USD',
    true,
    'dnd-players-handbook-2024',
    'affiliate',
    'https://www.amazon.com/s?k=2024+Player%27s+Handbook+Dungeons+%26+Dragons&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/book.svg',
    'Dungeons & Dragons 2024 Player’s Handbook',
    'Must-have',
    null,
    'tabletop',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'lego-mandalorian-helmet-75328',
    'LEGO Star Wars The Mandalorian Helmet (75328)',
    'Buildable Mandalorian helmet display set (75328) with 584 pieces.',
    100,
    'USD',
    true,
    'lego-mandalorian-helmet-75328',
    'affiliate',
    'https://www.amazon.com/s?k=LEGO+75328+The+Mandalorian+Helmet&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Mandalorian Helmet set',
    'Display piece',
    null,
    'lego',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'lego-luke-xwing-75301',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter (75301)',
    'Detailed X-Wing build with adjustable wings and minifigures (set 75301).',
    100,
    'USD',
    true,
    'lego-luke-xwing-75301',
    'affiliate',
    'https://www.amazon.com/s?k=LEGO+75301+Luke+Skywalker%27s+X-Wing+Fighter&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/lego.svg',
    'LEGO Star Wars Luke Skywalker’s X-Wing Fighter set',
    'Classic build',
    null,
    'lego',
    'Brad''s Amazon Picks'
  ),
  (
    gen_random_uuid(),
    'funko-pop-darth-vader-64557',
    'Funko Pop! Darth Vader (64557)',
    'Vinyl Darth Vader bobblehead from the Obi-Wan Kenobi series, approx. 5 in tall.',
    100,
    'USD',
    true,
    'funko-pop-darth-vader-64557',
    'affiliate',
    'https://www.amazon.com/s?k=Funko+Pop+Darth+Vader+64557&tag=bradleymatera-20',
    'amazon',
    'See price on Amazon',
    '/store/funko.svg',
    'Funko Pop Darth Vader collectible',
    'Desk flair',
    null,
    'collectible',
    'Brad''s Amazon Picks'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  active = EXCLUDED.active,
  file_key = EXCLUDED.file_key,
  product_type = EXCLUDED.product_type,
  affiliate_url = EXCLUDED.affiliate_url,
  affiliate_source = EXCLUDED.affiliate_source,
  display_price = EXCLUDED.display_price,
  image_url = EXCLUDED.image_url,
  image_alt = EXCLUDED.image_alt,
  badge = EXCLUDED.badge,
  featured_rank = EXCLUDED.featured_rank,
  category = EXCLUDED.category,
  collection = EXCLUDED.collection;

UPDATE products
SET active = false
WHERE slug = 'example-product';
