export const MUNICIPAL_SOURCES: Record<string, { label: string; url: string }> = {
  "web-developer-durand-davis-illinois": { label: "Village of Durand", url: "https://villageofdurand.com" },
  "web-developer-rockford-illinois": { label: "City of Rockford", url: "https://rockfordil.gov" },
  "web-developer-freeport-illinois": { label: "City of Freeport", url: "https://www.cityoffreeport.org" },
  "web-developer-pecatonica-illinois": { label: "Village of Pecatonica", url: "https://www.villageofpecatonica.com" },
  "web-developer-winnebago-illinois": { label: "Village of Winnebago", url: "https://www.villageofwinnebago.com" },
  "web-developer-loves-park-illinois": { label: "City of Loves Park", url: "https://cityoflovespark.com" },
  "web-developer-machesney-park-illinois": { label: "Village of Machesney Park", url: "https://machesneypark.org" },
  "web-developer-byron-illinois": { label: "City of Byron", url: "https://www.cityofbyron.com" },
  "web-developer-roscoe-illinois": { label: "Village of Roscoe", url: "https://www.villageofroscoe.com" },
  "web-developer-rockton-illinois": { label: "Village of Rockton", url: "https://www.rocktonil.gov" },
  "web-developer-south-beloit-illinois": { label: "City of South Beloit", url: "https://www.southbeloit.org" },
  "web-developer-beloit-wisconsin": { label: "City of Beloit", url: "https://www.beloitwi.gov" },
  "web-developer-janesville-wisconsin": { label: "City of Janesville", url: "https://www.janesvillewi.gov" },
  "web-developer-belvidere-illinois": { label: "City of Belvidere", url: "https://www.belvidereil.gov" },
  "web-developer-cherry-valley-illinois": { label: "Village of Cherry Valley", url: "https://www.cherryvalley.org" },
  "web-developer-oregon-illinois": { label: "City of Oregon", url: "https://cityoforegon.org" },
  "web-developer-mount-morris-illinois": { label: "Village of Mount Morris", url: "https://mtmorrisil.net" },
  "web-developer-rochelle-illinois": { label: "City of Rochelle", url: "https://www.cityofrochelle.net" },
  "web-developer-polo-illinois": { label: "City of Polo", url: "https://www.poloil.gov" },
  "web-developer-forreston-illinois": { label: "Village of Forreston", url: "https://villageofforreston.org" },
  "web-developer-dekalb-illinois": { label: "City of DeKalb", url: "https://www.cityofdekalb.com" },
  "web-developer-sycamore-illinois": { label: "City of Sycamore", url: "https://cityofsycamore.com" },
  "web-developer-sterling-illinois": { label: "City of Sterling", url: "https://www.sterling-il.gov" },
  "web-developer-rock-falls-illinois": { label: "City of Rock Falls", url: "https://www.rockfalls61071.net" },
  "web-developer-dixon-illinois": { label: "City of Dixon", url: "https://www.dixongov.com" },
  "web-developer-amboy-illinois": { label: "City of Amboy", url: "https://cityofamboy.org" },
  "web-developer-ashton-illinois": { label: "Village of Ashton", url: "https://www.ashtonil.com" },
  "web-developer-monroe-wisconsin": { label: "City of Monroe", url: "https://www.cityofmonroe.org" },
  "web-developer-brodhead-wisconsin": { label: "City of Brodhead", url: "https://www.cityofbrodheadwi.us" },
  "web-developer-evansville-wisconsin": { label: "City of Evansville", url: "https://www.ci.evansville.wi.gov" },
  "web-developer-edgerton-wisconsin": { label: "City of Edgerton", url: "https://www.cityofedgerton.com" },
  "web-developer-milton-wisconsin": { label: "City of Milton", url: "https://www.milton-wi.gov" },
  "web-developer-clinton-wisconsin": { label: "Village of Clinton", url: "https://www.clintonwi.us" },
};

export const COUNTY_SOURCES: Record<string, string> = {
  "Winnebago County": "https://wincoil.gov/",
  "Winnebago and Stephenson counties": "https://wincoil.gov/",
  "Stephenson County": "https://stephensoncountyil.gov/",
  "Ogle County": "https://www.oglecountyil.gov/",
  "Boone County": "https://www.boonecountyil.gov/",
  "DeKalb County": "https://dekalbcounty.org/",
  "Whiteside County": "https://www.whitesidecountyil.gov/",
  "Lee County": "https://www.leecountyil.com/",
  "Green County": "https://www.greencountywi.org/",
  "Rock County": "https://www.co.rock.wi.us/",
};
